# Generated by Django 2.2.5 on 2019-09-28 00:39

from django.db import migrations, models


def seed(apps, editor):
    Exchange = apps.get_model('market', 'Exchange')
    Exchange.objects.create(name='Binance')


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_market'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(seed),
    ]
