# Generated by Django 2.2.5 on 2019-09-28 00:41

from django.db import migrations, models
import django.db.models.deletion


def seed(apps, editor):
    ExchangeMarket = apps.get_model('market', 'ExchangeMarket')
    Exchange = apps.get_model('market', 'Exchange')
    Market = apps.get_model('market', 'Market')
    binance = Exchange.objects.get(name='Binance')
    btcusdt = Market.objects.get(name='BTCUSDT')
    ExchangeMarket.objects.create(exchange=binance, market=btcusdt)


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_exchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_markets', to='market.Exchange')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_markets', to='market.Market')),
            ],
            options={
                'db_table': 'market_exchange_market',
            },
        ),
        migrations.RunPython(seed),
    ]
