# Generated by Django 2.2.5 on 2019-09-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_exchangemarket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
