# Generated by Django 2.2.5 on 2019-09-28 00:59

from django.db import migrations, models


def seed(apps, editor):
    Exchange = apps.get_model('market', 'Exchange')
    Interval = apps.get_model('market', 'Interval')
    binance = Exchange.objects.get(name='Binance')
    intervals_names = ['1m', '3m', '5m', '15m', '30m', '1h', '2h', '4h', '6h', '8h', '12h', '1d', '3d', '1w', '1M']
    for name in intervals_names:
        interval = Interval.objects.get_or_create(name=name)
        binance.intervals.add(interval[0])


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='intervals',
            field=models.ManyToManyField(to='market.Interval'),
        ),
        migrations.RunPython(seed),
    ]
