# Generated by Django 2.2.5 on 2019-09-28 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_exchange_intervals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_at', models.DateTimeField()),
                ('close_at', models.DateTimeField()),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('volume', models.FloatField()),
                ('closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('exchange_market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.ExchangeMarket')),
                ('interval', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.Interval')),
            ],
        ),
    ]
